default_stages: [commit]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.10.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.4"
    hooks:
      - id: prettier
        exclude: "go.mod"
  - repo: https://github.com/golangci/golangci-lint
    rev: "v1.55.2"
    hooks:
      - id: golangci-lint
        args: ["--timeout", "3m0s"]
  - repo: https://github.com/segmentio/golines
    rev: "v0.11.0"
    hooks:
      - id: golines
